[package]
name = "adrive-sign-in"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adrive-api = { path = "../adrive-api" }
axum = "0.7.4"
tokio = "1.35.1"
